title: Qicheng Zhu's Homepage
page-top-title: Qicheng Zhu
top-section-bg-text: Stay Hungry, Stay Foolish
home-subtitle: Qicheng Zhu &ensp;|&ensp; 朱琪承
copyright-text: '&copy; Qicheng Zhu 2025. All Rights Reserved.'
